### PR TITLE
Add workflows for Python 3.12

### LINKED ISSUE #328: Add Python 3.12 support
- [x] Update tests
- [x] Update pyproject.toml

### PR DESCRIPTION
**Pull request by chrisjkuch**
Closes #328

### CODE REVIEW

**Comment by chrisjkuch** [comment]
Currently breaks with following error:
```
+ make create_environment
Examining conflict for setuptools ipython flake8 matplotlib pip wheel scikit-learn isort python:   0%|   Examining conflict for setuptools ipython flake8 pandas matplotlib pip numpy black wheel scikit-learn jupExamining conflict for setuptools ipython flake8 pandas matplotlib pip numpy black wheel scikit-learn jupExamining conflict for setuptools ipython flake8 matplotlib pip wheel isort:  12%|█▎        | 2/16 [00:12Examining conflict for setuptools ipython flake8 matplotlib pip wheel isort:  19%|█▉        | 3/16 [00:12Examining conflict for setuptools ipython flake8 pandas matplotlib pip numpy black wheel scikit-learn isoExamining conflict for setuptools ipython flake8 pandas matplotlib pip numpy black wheel scikit-learn isoExamining conflict for setuptools ipython flake8 pandas matplotlib pip numpy wheel scikit-learn jupyter iExamining conflict for setuptools ipython flake8 pandas matplotlib pip numpy wheel scikit-learn jupyter iExamining conflict for ipython jupyter:  31%|███▏      | 5/16 [00:34<01:04,  5.86s/it]                   Examining conflict for ipython pandas matplotlib numpy scikit-learn:  62%|██████▎   | 10/16 [00:37<00:13,Examining conflict for ipython pandas matplotlib numpy scikit-learn:  69%|██████▉   | 11/16 [00:37<00:07,Examining conflict for ipython flake8:  69%|██████▉   | 11/16 [00:47<00:07,  1.59s/it]                   Examining conflict for numpy scikit-learn pandas matplotlib:  94%|█████████▍| 15/16 [00:47<00:01,  1.50s/Examining conflict for pandas matplotlib: 100%|██████████| 16/16 [00:55<00:00,  1.50s/it]                Examining conflict for setuptools ipython flake8 matplotlib pip wheel scikit-learn isort python:   0%|   Examining conflict for setuptools ipython flake8 pandas matplotlib pip numpy black wheel scikit-learn jupExamining conflict for setuptools ipython flake8 pandas matplotlib pip numpy black wheel scikit-learn jupExamining conflict for setuptools ipython flake8 matplotlib pip wheel isort:  12%|█▎        | 2/16 [00:13Examining conflict for setuptools ipython flake8 matplotlib pip wheel isort:  19%|█▉        | 3/16 [00:13Examining conflict for setuptools ipython flake8 pandas matplotlib pip numpy black wheel scikit-learn isoExamining conflict for setuptools ipython flake8 pandas matplotlib pip numpy black wheel scikit-learn isoExamining conflict for setuptools ipython flake8 pandas matplotlib pip numpy wheel scikit-learn jupyter iExamining conflict for setuptools ipython flake8 pandas matplotlib pip numpy wheel scikit-learn jupyter iExamining conflict for ipython jupyter:  31%|███▏      | 5/16 [00:36<01:08,  6.19s/it]                   Examining conflict for ipython pandas matplotlib numpy scikit-learn:  62%|██████▎   | 10/16 [00:39<00:13,Examining conflict for ipython pandas matplotlib numpy scikit-learn:  69%|██████▉   | 11/16 [00:39<00:08,Examining conflict for ipython flake8:  69%|██████▉   | 11/16 [00:49<00:08,  1.68s/it]                   Examining conflict for numpy scikit-learn pandas matplotlib:  94%|█████████▍| 15/16 [00:50<00:01,  1.59s/Examining conflict for pandas matplotlib: 100%|██████████| 16/16 [00:58<00:00,  1.59s/it]
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package typing conflicts for:
flake8 -> typing
black -> mypy_extensions -> typing[version='>=3.7.4']
ipython -> typing_extensions -> typing[version='>=3.7.4']

Package numpy conflicts for:
pandas -> bottleneck[version='>=1.3.4'] -> numpy[version='>=1.16.4,<2.0a0|>=1.22.3,<2.0a0']
matplotlib -> matplotlib-base[version='>=3.8.0,<3.8.1.0a0'] -> numpy[version='>=1.15.4,<2.0a0|>=1.16.6,<2.0a0|>=1.20|>=1.21.5,<2.0a0|>=1.23.5,<2.0a0|>=1.26.0,<2.0a0|>=1.22.3,<2.0a0|>=1.19.2,<2.0a0|>=1.21.2,<2.0a0']
pandas -> numpy[version='>=1.11.3,<2.0a0|>=1.12.1,<2.0a0|>=1.13.3,<2.0a0|>=1.14.6,<2.0a0|>=1.15.4,<2.0a0|>=1.16,<2.0a0|>=1.20.3,<2.0a0|>=1.21.5,<2.0a0|>=1.23.5,<2.0a0|>=1.26.2,<2.0a0|>=1.26.0,<2.0a0|>=1.23,<2.0a0|>=1.21,<2.0a0|>=1.19.2,<2.0a0|>=1.21.2,<2.0a0|>=1.20.2,<2.0a0|>=1.16.6,<2.0a0|>=1.9.3,<2.0a0|>=1.9.3,<1.10.0a0|>=1.9']
matplotlib -> numpy[version='>=1.14.6,<2.0a0']
numpy
scikit-learn -> scipy[version='>=1.5.0'] -> numpy[version='>=1.15.1,<2.0a0|>=1.16,<1.23|>=1.19,<1.25.0|>=1.19,<1.26.0|>=1.19.5,<1.27.0|>=1.21.5,<1.28|>=1.26.2,<1.28|>=1.23.5,<1.28|>=1.26.0,<1.28|>=1.23,<1.27.0|>=1.21,<1.27.0|>=1.23,<1.26.0|>=1.21,<1.26.0|>=1.21,<1.25.0|>=1.21,<1.23|>=1.21.2,<1.23.0|>=1.16.6,<1.23.0']
scikit-learn -> numpy[version='<1.25|>=1.21.5,<2.0a0|>=1.26.0,<2.0a0|>=1.23.5,<2.0a0|>=1.19.5,<2.0a0|>=1.19.2,<2.0a0|>=1.16.6,<2.0a0|>=1.21.2,<2.0a0|>=1.14.6,<2.0a0|>=1.11.3,<2.0a0|>=1.9.3,<2.0a0']

Package pip conflicts for:
isort -> python[version='>=3.6.1,<4.0'] -> pip
matplotlib -> python[version='>=3.12,<3.13.0a0'] -> pip
ipython -> python[version='>=3.10,<3.11.0a0'] -> pip
wheel -> python[version='>=3.12,<3.13.0a0'] -> pip
scikit-learn -> python[version='>=3.12,<3.13.0a0'] -> pip
pandas -> python[version='>=3.10,<3.11.0a0'] -> pip
jupyter -> python[version='>=3.11,<3.12.0a0'] -> pip
pip
python=3.12 -> pip
flake8 -> python[version='>=3.12,<3.13.0a0'] -> pip
black -> python[version='>=3.12,<3.13.0a0'] -> pip
numpy -> python[version='>=3.12,<3.13.0a0'] -> pip

Package expat conflicts for:
numpy -> python[version='>=3.12,<3.13.0a0'] -> expat[version='>=2.5.0,<3.0a0']
wheel -> python[version='>=3.12,<3.13.0a0'] -> expat[version='>=2.5.0,<3.0a0']
python=3.12 -> expat[version='>=2.5.0,<3.0a0']
scikit-learn -> python[version='>=3.12,<3.13.0a0'] -> expat[version='>=2.5.0,<3.0a0']
setuptools -> python[version='>=3.12,<3.13.0a0'] -> expat[version='>=2.5.0,<3.0a0']
flake8 -> python[version='>=3.12,<3.13.0a0'] -> expat[version='>=2.5.0,<3.0a0']
ipython -> python[version='>=3.12,<3.13.0a0'] -> expat[version='>=2.5.0,<3.0a0']
isort -> python[version='>=3.6.1,<4.0'] -> expat[version='>=2.5.0,<3.0a0']
pip -> python[version='>=3.12,<3.13.0a0'] -> expat[version='>=2.5.0,<3.0a0']
matplotlib -> python[version='>=3.12,<3.13.0a0'] -> expat[version='>=2.5.0,<3.0a0']
pandas -> python[version='>=3.12,<3.13.0a0'] -> expat[version='>=2.5.0,<3.0a0']
black -> python[version='>=3.12,<3.13.0a0'] -> expat[version='>=2.5.0,<3.0a0']

Package entrypoints conflicts for:
flake8 -> entrypoints[version='>=0.3.0,<0.4.0']
jupyter -> nbconvert -> entrypoints[version='>=0.2.2']

Package backports conflicts for:
matplotlib -> backports.functools_lru_cache -> backports
isort -> backports.functools_lru_cache -> backports
ipython -> backports.shutil_get_terminal_size -> backports
flake8 -> configparser -> backports

Package certifi conflicts for:
wheel -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
flake8 -> setuptools[version='>=30.0.0'] -> certifi[version='>=2016.09|>=2016.9.26']
isort -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
ipython -> setuptools[version='>=18.5'] -> certifi[version='>=2016.09|>=2016.9.26']
pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
setuptools -> certifi[version='>=2016.09|>=2016.9.26']
matplotlib -> tornado -> certifi[version='>=2016.09|>=2016.9.26|>=2020.06.20']

Package enum34 conflicts for:
flake8 -> enum34
ipython -> traitlets[version='>=4.2'] -> enum34

Package flit-core conflicts for:
black -> typing_extensions[version='>=4.0.1'] -> flit-core[version='>=3.6,<4']
ipython -> typing_extensions -> flit-core[version='>=3.6,<4']

Package six conflicts for:
scikit-learn -> mkl-service[version='>=2,<3.0a0'] -> six
pandas -> python-dateutil[version='>=2.8.2'] -> six[version='>=1.5']
numpy -> mkl-service[version='>=2.3.0,<3.0a0'] -> six
ipython -> prompt-toolkit[version='>3.0.1,<3.1.0'] -> six[version='>=1.9.0']
matplotlib -> cycler[version='>=0.10'] -> six[version='>=1.5']

Package importlib_resources conflicts for:
matplotlib -> matplotlib-base[version='>=3.8.0,<3.8.1.0a0'] -> importlib_resources[version='>=3.2.0|>=5.2.0']
jupyter -> jupyterlab -> importlib_resources[version='>=1.4']

Package tomli conflicts for:
jupyter -> jupyterlab -> tomli
black -> tomli[version='>=1.1.0']

Package ca-certificates conflicts for:
pip -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
isort -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
jupyter -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
pandas -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
ipython -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
numpy -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
flake8 -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
scikit-learn -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
python=3.12 -> openssl[version='>=3.0.11,<4.0a0'] -> ca-certificates
wheel -> python -> ca-certificates
matplotlib -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
setuptools -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates

Package functools32 conflicts for:
flake8 -> functools32
matplotlib -> functools32

Package setuptools conflicts for:
pip -> setuptools
ipython -> pygments[version='>=2.4.0'] -> setuptools
setuptools
isort -> setuptools
flake8 -> pyflakes[version='>=1.5.0,<1.7.0'] -> setuptools
ipython -> setuptools[version='>=18.5']
wheel -> setuptools
matplotlib -> setuptools
scikit-learn -> joblib -> setuptools
flake8 -> setuptools[version='>=30.0.0']
python=3.12 -> pip -> setuptools

Package typing_extensions conflicts for:
ipython -> typing_extensions
matplotlib -> kiwisolver -> typing_extensions
flake8 -> importlib-metadata -> typing_extensions[version='>=3.6.4']
black -> typing_extensions[version='>=3.10.0.0|>=4.0.1']

Package importlib-metadata conflicts for:
black -> click[version='>=8.0.0'] -> importlib-metadata
jupyter -> ipykernel -> importlib-metadata[version='<5|>=4.8.3|>=3.6']
flake8 -> importlib-metadata

Package packaging conflicts for:
matplotlib -> matplotlib-base[version='>=3.8.0,<3.8.1.0a0'] -> packaging[version='>=20.0']
pandas -> numexpr[version='>=2.8.0'] -> packaging
jupyter -> ipykernel -> packaging
black -> packaging[version='>=22.0']

Package backports.functools_lru_cache conflicts for:
isort -> backports.functools_lru_cache
matplotlib -> backports.functools_lru_cache

Package llvm-openmp conflicts for:
scikit-learn -> llvm-openmp[version='>=10.0.0|>=12.0.0|>=14.0.6']
numpy -> libgfortran5[version='>=11.2.0'] -> llvm-openmp[version='>=8.0.0']

Package python-dateutil conflicts for:
matplotlib -> matplotlib-base[version='>=3.8.0,<3.8.1.0a0'] -> python-dateutil[version='>=2.1|>=2.7']
pandas -> python-dateutil[version='>=2.5.*|>=2.6.1|>=2.7.3|>=2.8.1|>=2.8.2']
matplotlib -> python-dateutil

Package futures conflicts for:
matplotlib -> tornado[version='>=5'] -> futures
jupyter -> jupyterlab -> futures
isort -> futures

Package libcxxabi conflicts for:
pandas -> libcxx[version='>=4.0.1'] -> libcxxabi==4.0.1[build='hcfea43d_1|hebd6815_0']
matplotlib -> libcxx[version='>=4.0.1'] -> libcxxabi==4.0.1[build='hcfea43d_1|hebd6815_0']
scikit-learn -> libcxx[version='>=4.0.1'] -> libcxxabi==4.0.1[build='hcfea43d_1|hebd6815_0']

Package wheel conflicts for:
python=3.12 -> pip -> wheel
pip -> wheel
wheel

Package ipython conflicts for:
jupyter -> ipykernel -> ipython[version='>=4.0.0|>=4.0|>=5.0|>=7.23.1|>=7.23.1,<8.0|>=6.1.0']
ipythonThe following specifications were found to be incompatible with your system:

  - feature:/osx-64::__osx==10.16=0
  - feature:|@/osx-64::__osx==10.16=0
  - matplotlib -> matplotlib-base[version='>=3.8.0,<3.8.1.0a0'] -> __osx[version='>=10.11|>=10.12']

Your installed version is: 10.16
```

**Comment by jayqi** [comment]
Okay, got this working by:

1. Replacing the weird `jupyter` metapackage with `jupyterlab` and `notebook` directly. I'm not really sure what the point of this is—it is actually owned by Jupyter project people—but it's an extra layer of something to go wrong that seems worth removing.
2. Changing to conda-forge. It still wasn't working with default channel.
    - As has been pointed out elsewhere, in 2020 Anaconda [changed their TOS](https://www.anaconda.com/blog/sustaining-our-stewardship-of-the-open-source-data-science-community) to make the defaults channel some form of free-for-noncommercial-use. It's probably a better opinionated default to direct people to conda-forge. 
    - For whatever reason, this is building faster than when I was experimenting in #319. Maybe getting rid of the `juptyer` metapackage was the key. 🤷

**Comment by jayqi** [comment]
Okay, got this working by:

1. Replacing the weird `jupyter` metapackage with both `jupyterlab` and `notebook` directly. I'm not really sure what the point of this is—it is actually owned by Jupyter project people—but it's an extra layer of something to go wrong that seems worth removing.
2. Changing to conda-forge. It still wasn't working with defaults channel.
    - As has been pointed out elsewhere, in 2020 Anaconda [changed their TOS](https://www.anaconda.com/blog/sustaining-our-stewardship-of-the-open-source-data-science-community) to make the defaults channel some form of free-for-noncommercial-use. It's probably a better opinionated default to direct people to conda-forge. 
    - For whatever reason, this is building faster than when I was experimenting in #319. Maybe getting rid of the `juptyer` metapackage was the key. 🤷  

@pjbull Not sure if you have any opinions about conda-forge or not.

**Review by pjbull — APPROVED** [review]
I like the decisions here—they make sense. Will add a note on that to the opinions/discussion as well.

Thanks for tracking down the problematic package!

**Pull request merged**
