### PR TITLE
adds visualization directory to src

### PR DESCRIPTION
**Pull request by jbrambleDC**
@pjbull Here is a PR that corresponds to #12 . let me know if you want the base filename to change to something else.

### CODE REVIEW

**Comment by pjbull** [comment]
Nice, thanks @jbrambleDC! 👍 

A few quick things:
 1) Can we change `visualizations` to `visualization` (so we can write `from visualization import`)
 2) And `visualize_results.py` for `visualize.py` (since by default, folks will want to visualize things other than just the results)
 3) Could you update the ascii tree to include the changes in `{{ cookiecutter.repo_name }}/README.md` and `docs/docs/index.md`

**Comment by jbrambleDC** [comment]
@pjbull that should do it!

**Comment by pjbull** [comment]
Thanks!

**Comment by jbrambleDC** [comment]
@pjbull No, Thank you! Im going to start using this immediately, its pretty awesome. Also, big fan/supporter of everything driven data does.

**Pull request merged**
