### PR TITLE
make gsutil rsync recursive

### PR DESCRIPTION
**Pull request by KBodolai**
Small change to allow gsutil to do rsync recursively, syncing all the folders.

Context: We had some issues using it with gcloud, since `make sync_data_up` would not upload all the data folders. Adding the -r flag fixes this issue.

### CODE REVIEW

**Comment by pjbull** [comment]
Thanks @KBodolai. Rebasing on to the latest `v2` should work now to run the tests.

**Comment by KBodolai** [comment]
ok, I've done that, hopefully it'll be it!

**Comment by KBodolai** [comment]
ok, so these passed (yay!) 

There's another parameter that can be fed to gsutil for threaded processing (-m), which provides huge performance boosts, although they mention [in some cases it may slow the syncing down](https://cloud.google.com/storage/docs/gsutil/commands/rsync).

I believe it will typically only result in speedups for the setting this is used in, but not quite certain, what do you think?

**Comment by pjbull** [comment]
@KBodolai I agree that 99% of the use cases here will be cloud <-> local, not local <-> local so `-m` likely makes sense. Happy to wait on this til that id added

**Comment by KBodolai** [comment]
right, I'll add it and set up a test project to double check it does well, I'll ping you when it's ready :)

**Comment by KBodolai** [comment]
@pjbull , actually, I stayed a bit late after work and tested if with a bunch of heavy lidar files, all working fine!

**Pull request merged**
